<?php

namespace Database\Seeders;

use App\Models\BaremoModel;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BaremoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $baremo = [
            [
                'percentil' => '99',
                'valor' => '24',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '1',
            ],    //1
            [
                'percentil' => '95',
                'valor' => '23',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '1',
            ],
            [
                'percentil' => '90',
                'valor' => '22',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '1',
            ],
            [
                'percentil' => '80',
                'valor' => '21',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '1',
            ],
            [
                'percentil' => '75',
                'valor' => '20',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '1',
            ],
            [
                'percentil' => '70',
                'valor' => null,
                'limite_inf' => '18',
                'limite_sup' => '19',
                'id_usuario' => '1',
                'id_area' => '1',
            ],
            [
                'percentil' => '60',
                'valor' => null,
                'limite_inf' => '14',
                'limite_sup' => '16',
                'id_usuario' => '1',
                'id_area' => '1',
            ],
            [
                'percentil' => '50',
                'valor' => '13',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '1',
            ],
            [
                'percentil' => '40',
                'valor' => '12',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '1',
            ],
            [
                'percentil' => '25',
                'valor' => '11',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '1',
            ],
            [
                'percentil' => '10',
                'valor' => '10',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '1',
            ],
            [
                'percentil' => '5',
                'valor' => '9',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '1',
            ],
            [
                'percentil' => '1',
                'valor' => '8',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '1',
            ],
            //cien
            [
                'percentil' => '99',
                'valor' => '24',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '2',
            ],    //1
            [
                'percentil' => '95',
                'valor' => '23',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '2',
            ],
            [
                'percentil' => '90',
                'valor' => '22',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '2',
            ],
            [
                'percentil' => '80',
                'valor' => '21',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '2',
            ],
            [
                'percentil' => '75',
                'valor' => '20',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '2',
            ],
            [
                'percentil' => '70',
                'valor' => '19',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '2',
            ],
            [
                'percentil' => '60',
                'valor' => '18',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '2',
            ],
            [
                'percentil' => '50',
                'valor' => null,
                'limite_inf' => '15',
                'limite_sup' => '17',
                'id_usuario' => '1',
                'id_area' => '2',
            ],
            [
                'percentil' => '40',
                'valor' => null,
                'limite_inf' => '13',
                'limite_sup' => '14',
                'id_usuario' => '1',
                'id_area' => '2',
            ],
            [
                'percentil' => '25',
                'valor' => '12',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '2',
            ],
            [
                'percentil' => '10',
                'valor' => null,
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '2',
            ],
            [
                'percentil' => '5',
                'valor' => '8',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '2',
            ],
            [
                'percentil' => '1',
                'valor' => null,
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '2',
            ],

            /** diseño */

            [
                'percentil' => '99',
                'valor' => '21',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '3',
            ],    //1
            [
                'percentil' => '95',
                'valor' => '20',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '3',
            ],
            [
                'percentil' => '90',
                'valor' => '19',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '3',
            ],
            [
                'percentil' => '80',
                'valor' => '18',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '3',
            ],
            [
                'percentil' => '75',
                'valor' => '17',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '3',
            ],
            [
                'percentil' => '70',
                'valor' => '16',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '3',
            ],
            [
                'percentil' => '60',
                'valor' => '15',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '3',
            ],
            [
                'percentil' => '50',
                'valor' => null,
                'limite_inf' => '13',
                'limite_sup' => '14',
                'id_usuario' => '1',
                'id_area' => '3',
            ],
            [
                'percentil' => '40',
                'valor' => null,
                'limite_inf' => '10',
                'limite_sup' => '12',
                'id_usuario' => '1',
                'id_area' => '3',
            ],
            [
                'percentil' => '25',
                'valor' => null,
                'limite_inf' => '8',
                'limite_sup' => '9',
                'id_usuario' => '1',
                'id_area' => '3',
            ],
            [
                'percentil' => '10',
                'valor' => '8',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '3',
            ],
            [
                'percentil' => '5',
                'valor' => null,
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '3',
            ],
            [
                'percentil' => '1',
                'valor' => null,
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '3',
            ],

            /** tecno */
            [
                'percentil' => '99',
                'valor' => '24',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '4',
            ],    //1
            [
                'percentil' => '95',
                'valor' => '23',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '4',
            ],
            [
                'percentil' => '90',
                'valor' => '22',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '4',
            ],
            [
                'percentil' => '80',
                'valor' => '21',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '4',
            ],
            [
                'percentil' => '75',
                'valor' => '20',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '4',
            ],
            [
                'percentil' => '70',
                'valor' => '19',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '4',
            ],
            [
                'percentil' => '60',
                'valor' => null,
                'limite_inf' => '17',
                'limite_sup' => '18',
                'id_usuario' => '1',
                'id_area' => '4',
            ],
            [
                'percentil' => '50',
                'valor' => null,
                'limite_inf' => '15',
                'limite_sup' => '16',
                'id_usuario' => '1',
                'id_area' => '4',
            ],
            [
                'percentil' => '40',
                'valor' => null,
                'limite_inf' => '13',
                'limite_sup' => '14',
                'id_usuario' => '1',
                'id_area' => '4',
            ],
            [
                'percentil' => '25',
                'valor' => null,
                'limite_inf' => '11',
                'limite_sup' => '12',
                'id_usuario' => '1',
                'id_area' => '4',
            ],
            [
                'percentil' => '10',
                'valor' => '10',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '4',
            ],
            [
                'percentil' => '5',
                'valor' => '9',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '4',
            ],
            [
                'percentil' => '1',
                'valor' => '8',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '4',
            ],
            /* Gastronomia */
            [
                'percentil' => '99',
                'valor' => '18',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '5',
            ],    //1
            [
                'percentil' => '95',
                'valor' => '17',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '5',
            ],
            [
                'percentil' => '90',
                'valor' => '16',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '5',
            ],
            [
                'percentil' => '80',
                'valor' => '15',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '5',
            ],
            [
                'percentil' => '75',
                'valor' => '14',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '5',
            ],
            [
                'percentil' => '70',
                'valor' => '13',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '5',
            ],
            [
                'percentil' => '60',
                'valor' => '12',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '5',
            ],
            [
                'percentil' => '50',
                'valor' => '11',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '5',
            ],
            [
                'percentil' => '40',
                'valor' => '10',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '5',
            ],
            [
                'percentil' => '25',
                'valor' => '9',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '5',
            ],
            [
                'percentil' => '10',
                'valor' => '8',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '5',
            ],
            [
                'percentil' => '5',
                'valor' => '7',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '5',
            ],
            [
                'percentil' => '1',
                'valor' => '6',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '5',
            ],
            /** natura */
            [
                'percentil' => '99',
                'valor' => '24',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '6',
            ],    //1
            [
                'percentil' => '95',
                'valor' => '23',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '6',
            ],
            [
                'percentil' => '90',
                'valor' => '22',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '6',
            ],
            [
                'percentil' => '80',
                'valor' => '21',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '6',
            ],
            [
                'percentil' => '75',
                'valor' => null,
                'limite_inf' => '18',
                'limite_sup' => '20',
                'id_usuario' => '1',
                'id_area' => '6',
            ],
            [
                'percentil' => '70',
                'valor' => null,
                'limite_inf' => '15',
                'limite_sup' => '17',
                'id_usuario' => '1',
                'id_area' => '6',
            ],
            [
                'percentil' => '60',
                'valor' => '14',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '6',
            ],
            [
                'percentil' => '50',
                'valor' => '13',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '6',
            ],
            [
                'percentil' => '40',
                'valor' => '12',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '6',
            ],
            [
                'percentil' => '25',
                'valor' => null,
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '6',
            ],
            [
                'percentil' => '10',
                'valor' => null,
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '6',
            ],
            [
                'percentil' => '5',
                'valor' => null,
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '6',
            ],
            [
                'percentil' => '1',
                'valor' => null,
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '6',
            ],

            /** sanita */
            [
                'percentil' => '99',
                'valor' => '21',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '7',
            ],    //1
            [
                'percentil' => '95',
                'valor' => '20',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '7',
            ],
            [
                'percentil' => '90',
                'valor' => '19',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '7',
            ],
            [
                'percentil' => '80',
                'valor' => '18',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '7',
            ],
            [
                'percentil' => '75',
                'valor' => null,
                'limite_inf' => '15',
                'limite_sup' => '17',
                'id_usuario' => '1',
                'id_area' => '7',
            ],
            [
                'percentil' => '70',
                'valor' => '14',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '7',
            ],
            [
                'percentil' => '60',
                'valor' => '13',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '7',
            ],
            [
                'percentil' => '50',
                'valor' => '12',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '7',
            ],
            [
                'percentil' => '40',
                'valor' => '11',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '7',
            ],
            [
                'percentil' => '25',
                'valor' => null,
                'limite_inf' => '9',
                'limite_sup' => '10',
                'id_usuario' => '1',
                'id_area' => '7',
            ],
            [
                'percentil' => '10',
                'valor' => '7',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '7',
            ],
            [
                'percentil' => '5',
                'valor' => null,
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '7',
            ],
            [
                'percentil' => '1',
                'valor' => null,
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '7',
            ],

            /** asistencial */

            [
                'percentil' => '99',
                'valor' => '21',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '8',
            ],    //1
            [
                'percentil' => '95',
                'valor' => '20',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '8',
            ],
            [
                'percentil' => '90',
                'valor' => '19',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '8',
            ],
            [
                'percentil' => '80',
                'valor' => '18',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '8',
            ],
            [
                'percentil' => '75',
                'valor' => null,
                'limite_inf' => '16',
                'limite_sup' => '17',
                'id_usuario' => '1',
                'id_area' => '8',
            ],
            [
                'percentil' => '70',
                'valor' => null,
                'limite_inf' => '14',
                'limite_sup' => '15',
                'id_usuario' => '1',
                'id_area' => '8',
            ],
            [
                'percentil' => '60',
                'valor' => '13',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '8',
            ],
            [
                'percentil' => '50',
                'valor' => null,
                'limite_inf' => '11',
                'limite_sup' => '12',
                'id_usuario' => '1',
                'id_area' => '8',
            ],
            [
                'percentil' => '40',
                'valor' => '10',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '8',
            ],
            [
                'percentil' => '25',
                'valor' => '9',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '8',
            ],
            [
                'percentil' => '10',
                'valor' => '8',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '8',
            ],
            [
                'percentil' => '5',
                'valor' => '7',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '8',
            ],
            [
                'percentil' => '1',
                'valor' => null,
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '8',
            ],

            /** Juri */
            [
                'percentil' => '99',
                'valor' => '24',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '9',
            ],    //1
            [
                'percentil' => '95',
                'valor' => '23',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '9',
            ],
            [
                'percentil' => '90',
                'valor' => '22',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '9',
            ],
            [
                'percentil' => '80',
                'valor' => '21',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '9',
            ],
            [
                'percentil' => '75',
                'valor' => null,
                'limite_inf' => '19',
                'limite_sup' => '20',
                'id_usuario' => '1',
                'id_area' => '9',
            ],
            [
                'percentil' => '70',
                'valor' => null,
                'limite_inf' => '17',
                'limite_sup' => '18',
                'id_usuario' => '1',
                'id_area' => '9',
            ],
            [
                'percentil' => '60',
                'valor' => null,
                'limite_inf' => '15',
                'limite_sup' => '16',
                'id_usuario' => '1',
                'id_area' => '9',
            ],
            [
                'percentil' => '50',
                'valor' => null,
                'limite_inf' => '13',
                'limite_sup' => '14',
                'id_usuario' => '1',
                'id_area' => '9',
            ],
            [
                'percentil' => '40',
                'valor' => '12',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '9',
            ],
            [
                'percentil' => '25',
                'valor' => '11',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '9',
            ],
            [
                'percentil' => '10',
                'valor' => '10',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '9',
            ],
            [
                'percentil' => '5',
                'valor' => '9',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '9',
            ],
            [
                'percentil' => '1',
                'valor' => '8',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '9',
            ],
            /** Economia */
            [
                'percentil' => '99',
                'valor' => '24',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '10',
            ],    //1
            [
                'percentil' => '95',
                'valor' => '23',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '10',
            ],
            [
                'percentil' => '90',
                'valor' => '22',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '10',
            ],
            [
                'percentil' => '80',
                'valor' => '21',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '10',
            ],
            [
                'percentil' => '75',
                'valor' => null,
                'limite_inf' => '19',
                'limite_sup' => '20',
                'id_usuario' => '1',
                'id_area' => '10',
            ],
            [
                'percentil' => '70',
                'valor' => null,
                'limite_inf' => '17',
                'limite_sup' => '18',
                'id_usuario' => '1',
                'id_area' => '10',
            ],
            [
                'percentil' => '60',
                'valor' => null,
                'limite_inf' => '15',
                'limite_sup' => '16',
                'id_usuario' => '1',
                'id_area' => '10',
            ],
            [
                'percentil' => '50',
                'valor' => '14',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '10',
            ],
            [
                'percentil' => '40',
                'valor' => null,
                'limite_inf' => '12',
                'limite_sup' => '13',
                'id_usuario' => '1',
                'id_area' => '10',
            ],
            [
                'percentil' => '25',
                'valor' => null,
                'limite_inf' => '10',
                'limite_sup' => '11',
                'id_usuario' => '1',
                'id_area' => '10',
            ],
            [
                'percentil' => '10',
                'valor' => '9',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '10',
            ],
            [
                'percentil' => '5',
                'valor' => null,
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '10',
            ],
            [
                'percentil' => '1',
                'valor' => null,
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '10',
            ],

            /** comunicacional */

            [
                'percentil' => '99',
                'valor' => '27',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '11',
            ],    //1
            [
                'percentil' => '95',
                'valor' => '26',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '11',
            ],
            [
                'percentil' => '90',
                'valor' => '25',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '11',
            ],
            [
                'percentil' => '80',
                'valor' => null,
                'limite_inf' => '22',
                'limite_sup' => '24',
                'id_usuario' => '1',
                'id_area' => '11',
            ],
            [
                'percentil' => '75',
                'valor' => '21',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '11',
            ],
            [
                'percentil' => '70',
                'valor' => null,
                'limite_inf' => '19',
                'limite_sup' => '20',
                'id_usuario' => '1',
                'id_area' => '11',
            ],
            [
                'percentil' => '60',
                'valor' => null,
                'limite_inf' => '17',
                'limite_sup' => '18',
                'id_usuario' => '1',
                'id_area' => '11',
            ],
            [
                'percentil' => '50',
                'valor' => '14',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '11',
            ],
            [
                'percentil' => '40',
                'valor' => '13',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '11',
            ],
            [
                'percentil' => '25',
                'valor' => '12',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '11',
            ],
            [
                'percentil' => '10',
                'valor' => null,
                'limite_inf' => '10',
                'limite_sup' => '11',
                'id_usuario' => '1',
                'id_area' => '11',
            ],
            [
                'percentil' => '5',
                'valor' => '9',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '11',
            ],
            [
                'percentil' => '1',
                'valor' => '9',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '11',
            ],
            /*** huma */
            [
                'percentil' => '99',
                'valor' => '24',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '12',
            ],    //1
            [
                'percentil' => '95',
                'valor' => '23',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '12',
            ],
            [
                'percentil' => '90',
                'valor' => '22',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '12',
            ],
            [
                'percentil' => '80',
                'valor' => '21',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '12',
            ],
            [
                'percentil' => '75',
                'valor' => '20',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '12',
            ],
            [
                'percentil' => '70',
                'valor' => null,
                'limite_inf' => '17',
                'limite_sup' => '19',
                'id_usuario' => '1',
                'id_area' => '12',
            ],
            [
                'percentil' => '60',
                'valor' => null,
                'limite_inf' => '15',
                'limite_sup' => '16',
                'id_usuario' => '1',
                'id_area' => '12',
            ],
            [
                'percentil' => '50',
                'valor' => '14',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '12',
            ],
            [
                'percentil' => '40',
                'valor' => '13',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '12',
            ],
            [
                'percentil' => '25',
                'valor' => null,
                'limite_inf' => '11',
                'limite_sup' => '12',
                'id_usuario' => '1',
                'id_area' => '12',
            ],
            [
                'percentil' => '10',
                'valor' => null,
                'limite_inf' => '9',
                'limite_sup' => '10',
                'id_usuario' => '1',
                'id_area' => '12',
            ],
            [
                'percentil' => '5',
                'valor' => '8',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '12',
            ],
            [
                'percentil' => '1',
                'valor' => null,
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '12',
            ],

            /** Artist */
            [
                'percentil' => '99',
                'valor' => '24',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '13',
            ],    //1
            [
                'percentil' => '95',
                'valor' => '23',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '13',
            ],
            [
                'percentil' => '90',
                'valor' => '22',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '13',
            ],
            [
                'percentil' => '80',
                'valor' => '21',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '13',
            ],
            [
                'percentil' => '75',
                'valor' => '20',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '13',
            ],
            [
                'percentil' => '70',
                'valor' => null,
                'limite_inf' => '17',
                'limite_sup' => '19',
                'id_usuario' => '1',
                'id_area' => '13',
            ],
            [
                'percentil' => '60',
                'valor' => null,
                'limite_inf' => '15',
                'limite_sup' => '16',
                'id_usuario' => '1',
                'id_area' => '13',
            ],
            [
                'percentil' => '50',
                'valor' => '14',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '13',
            ],
            [
                'percentil' => '40',
                'valor' => '13',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '13',
            ],
            [
                'percentil' => '25',
                'valor' => null,
                'limite_inf' => '11',
                'limite_sup' => '12',
                'id_usuario' => '1',
                'id_area' => '13',
            ],
            [
                'percentil' => '10',
                'valor' => null,
                'limite_inf' => '9',
                'limite_sup' => '10',
                'id_usuario' => '1',
                'id_area' => '13',
            ],
            [
                'percentil' => '5',
                'valor' => '8',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '13',
            ],
            [
                'percentil' => '1',
                'valor' => null,
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '13',
            ],

            /** music */
            [
                'percentil' => '99',
                'valor' => '27',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '14',
            ],    //1
            [
                'percentil' => '95',
                'valor' => '26',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '14',
            ],
            [
                'percentil' => '90',
                'valor' => '25',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '14',
            ],
            [
                'percentil' => '80',
                'valor' => null,
                'limite_inf' => '23',
                'limite_sup' => '24',
                'id_usuario' => '1',
                'id_area' => '14',
            ],
            [
                'percentil' => '75',
                'valor' => null,
                'limite_inf' => '21',
                'limite_sup' => '22',
                'id_usuario' => '1',
                'id_area' => '14',
            ],
            [
                'percentil' => '70',
                'valor' => null,
                'limite_inf' => '19',
                'limite_sup' => '20',
                'id_usuario' => '1',
                'id_area' => '14',
            ],
            [
                'percentil' => '60',
                'valor' => null,
                'limite_inf' => '16',
                'limite_sup' => '18',
                'id_usuario' => '1',
                'id_area' => '14',
            ],
            [
                'percentil' => '50',
                'valor' => null,
                'limite_inf' => '13',
                'limite_sup' => '25',
                'id_usuario' => '1',
                'id_area' => '14',
            ],
            [
                'percentil' => '40',
                'valor' => null,
                'limite_inf' => '10',
                'limite_sup' => '12',
                'id_usuario' => '1',
                'id_area' => '14',
            ],
            [
                'percentil' => '25',
                'valor' => '9',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '14',
            ],
            [
                'percentil' => '10',
                'valor' => '9',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '14',
            ],
            [
                'percentil' => '5',
                'valor' => null,
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '14',
            ],
            [
                'percentil' => '1',
                'valor' => null,
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '14',
            ],

            /** lingu */
            [
                'percentil' => '99',
                'valor' => '18',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '15',
            ],    //1
            [
                'percentil' => '95',
                'valor' => '17',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '15',
            ],
            [
                'percentil' => '90',
                'valor' => '16',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '15',
            ],
            [
                'percentil' => '80',
                'valor' => '15',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '15',
            ],
            [
                'percentil' => '75',
                'valor' => '14',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '15',
            ],
            [
                'percentil' => '70',
                'valor' => '13',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '15',
            ],
            [
                'percentil' => '60',
                'valor' => '12',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '15',
            ],
            [
                'percentil' => '50',
                'valor' => '11',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '15',
            ],
            [
                'percentil' => '40',
                'valor' => '10',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '15',
            ],
            [
                'percentil' => '25',
                'valor' => '9',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '15',
            ],
            [
                'percentil' => '10',
                'valor' => '8',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '15',
            ],
            [
                'percentil' => '5',
                'valor' => '7',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '15',
            ],
            [
                'percentil' => '1',
                'valor' => '6',
                'limite_inf' => null,
                'limite_sup' => null,
                'id_usuario' => '1',
                'id_area' => '15',
            ],

        ];

        // Iterar sobre las áreas y guardarlas en la base de datos
        foreach ($baremo as $area) {
            BaremoModel::create($area);
        }
    }
}
